Repository theforeman/foreman_azure_rm, pull requests merged in 2020-06, with the labels that each got.

#66 Correct syntax highlighting in README
  README.md
Labels: Ready for Merge

#89 Update Readme.md for 2.1.x
  README.md
Labels: Needs testing, Waiting on contributor

#90 Fixes #30027 - Cannot read property 'aDataSort' of undefined
  app/views/compute_resources_vms/index/_azurerm.html.erb
Labels: Needs testing

#88 Fixes #29819 - Support byos images on azurerm
  app/models/concerns/foreman_azure_rm/vm_extensions/managed_vm.rb
  app/views/images/form/_azurerm.html.erb
  lib/foreman_azure_rm/engine.rb
Labels: Needs re-review, Needs testing

#91 Bump 2.1.1
  lib/foreman_azure_rm/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
