Repository theforeman/foreman_azure_rm, pull requests merged in 2020-04, with the labels that each got.

#71 Fixes #28790 - Add Volumes capability
  app/models/concerns/foreman_azure_rm/vm_extensions/managed_vm.rb
  app/models/foreman_azure_rm/azure_rm.rb
  app/models/foreman_azure_rm/azure_rm_compute.rb
  app/views/compute_resources_vms/form/azurerm/_base.html.erb
  app/views/compute_resources_vms/form/azurerm/_volume.html.erb
  lib/foreman_azure_rm/azure_sdk_adapter.rb
Labels: Needs testing, Ready for Merge

#81 Fixes #29501 - Add Internationalization support
  locale/Makefile
  locale/en/foreman_azure_rm.po
  locale/foreman_azure_rm.pot
Labels: Needs testing

#83 Fixes #29586 - Move Travis to postgres
  .travis.yml
Labels: Needs testing, Not yet reviewed

#79 Fixes #29222 - Dynamically load regions based on subscription
  app/helpers/azure_compute_resource_helper.rb
  app/models/foreman_azure_rm/azure_rm.rb
  app/views/compute_resources/form/_azurerm.html.erb
  foreman_azure_rm.gemspec
  lib/foreman_azure_rm.rb
  lib/foreman_azure_rm/azure_sdk_adapter.rb
  lib/foreman_azure_rm/engine.rb
  test/functional/azure_rm_test.rb
  test/unit/azure_rm_test.rb
Labels: Needs testing, Waiting on contributor
