Repository theforeman/foreman_azure_rm, pull requests merged in 2021-03, with the labels that each got.

#103 Fixes #31938 - CVE-2021-3413 Azure compute resource secret_key leak
  app/views/api/v2/compute_resources/azurerm.json.rabl
Labels: Needs testing

#100 Refs #31188 - Remove Gov Cloud from planned features
  README.md
Labels: Needs re-review, Needs testing

#104 Bump version to 2.2.0
  lib/foreman_azure_rm/version.rb
Labels: Needs testing, Waiting on contributor

#106 Satellite 6.9 Cherry picks
  app/helpers/azure_compute_resource_helper.rb
  app/views/compute_resources/form/_azurerm.html.erb
Labels: Ready for Merge

#108 Implement custom size for OS disk
  app/models/concerns/foreman_azure_rm/vm_extensions/managed_vm.rb
  app/models/foreman_azure_rm/azure_rm.rb
  app/models/foreman_azure_rm/azure_rm_compute.rb
  app/views/compute_resources_vms/form/azurerm/_base.html.erb
Labels: Ready for Merge

#109 Enable windows type vm
  app/models/concerns/foreman_azure_rm/vm_extensions/managed_vm.rb
  app/models/foreman_azure_rm/azure_rm.rb
Labels: Ready for Merge

#111 Refs #31837 - Update docs button to use Foreman plugin helper
  app/helpers/azure_compute_resource_helper.rb
  app/views/compute_resources/form/_azurerm.html.erb
Labels: Ready for Merge

#110 Fixes #32123 - Bump Gem versions to latest and update CHANGELOG
  CHANGELOG.md
  foreman_azure_rm.gemspec
Labels: Ready for Merge
