Repository theforeman/foreman_azure_rm, pull requests merged in 2022-11, with the labels that each got.

#165 Pin GitHub actions to a major version
  .github/workflows/main.yml
Labels: Ready for Merge

#168 Fix tests by using Postgres 14
  .github/workflows/main.yml
Labels: Ready for Merge

#167 Bump version to 2.2.7 and update changelog
  CHANGELOG.md
  lib/foreman_azure_rm/version.rb
Labels: Needs re-review, Waiting on contributor

#169 Revert "Bump version to 2.2.7 and update changelog"
  CHANGELOG.md
  lib/foreman_azure_rm/version.rb
Labels: Not yet reviewed, Waiting on contributor

#170 Bump version to 2.2.8 and update changelog
  CHANGELOG.md
  lib/foreman_azure_rm/version.rb
Labels: Not yet reviewed, Waiting on contributor

#171 Fix up changelog for 2.2.8
  CHANGELOG.md
Labels: Ready for Merge
